<?php

/**
 * This file is part of the miBadger package.
 *
 * @author Michael Webbers <michael@webbers.io>
 * @license http://opensource.org/licenses/Apache-2.0 Apache v2 License
 */

namespace miBadger\Http;

use miBadger\Enum\Enum;

/**
 * The status code class.
 *
 * @since 1.0.0
 */
class StatusCode extends Enum
{
	const INFORMATIONAL_CONTINUE = 100;
	const INFORMATIONAL_SWITCHING_PROTOCOL = 101;
	const INFORMATIONAL_PROGRESSING = 102;
	const SUCCESFULL_OK = 200;
	const SUCCESFULL_CREATED = 201;
	const SUCCESFULL_ACCEPTED = 202;
	const SUCCESFULL_NON_AUTORITATIVE_INFORMATION = 203;
	const SUCCESFULL_NO_CONTENT = 204;
	const SUCCESFULL_RESET_CONTENT = 205;
	const SUCCESFULL_PARTIAL_CONTENT = 206;
	const MULTI_STATUS = 207;
	const ALREADY_REPORTED = 208;
	const REDIRECTION_MULTIPLE_CHOICES = 300;
	const REDIRECTION_MOVED_PERMANENTLY = 301;
	const REDIRECTION_FOUND = 302;
	const REDIRECTION_SEE_OTHER = 303;
	const REDIRECTION_NOT_MODIFIED = 304;
	const REDIRECTION_USE_PROXY = 305;
	const SWITCH_PROXY = 306;
	const REDIRECTION_TEMPORARY_REDIRECT = 307;
	const ERROR_CLIENT_BAD_REQUEST = 400;
	const ERROR_CLIENT_UNAUTHORIZED = 401;
	const ERROR_CLIENT_PAYMENT_REQUIRED = 402;
	const ERROR_CLIENT_FORBIDDEN = 403;
	const ERROR_CLIENT_NOT_FOUND = 404;
	const ERROR_CLIENT_METHOD_NOT_ALLOWED = 405;
	const ERROR_CLIENT_NOT_ACCEPTABLE = 406;
	const ERROR_CLIENT_PROXY_AUTHENTICATION_REQUIRED = 407;
	const ERROR_CLIENT_REQUEST_TIME_OUT = 408;
	const ERROR_CLIENT_CONFLICT = 409;
	const ERROR_CLIENT_GONE = 410;
	const ERROR_CLIENT_LENGTH_REQUIRED = 411;
	const ERROR_CLIENT_PRECONDITION_FAILED = 412;
	const ERROR_CLIENT_REQUEST_ENTITY_TOO_LARGE = 413;
	const ERROR_CLIENT_REQUEST_URI_TOO_LONG = 414;
	const ERROR_CLIENT_UNSUPPORTED_MEDIA = 415;
	const ERROR_CLIENT_REQUEST_RANGE_NOT_SATISFIABLE = 416;
	const ERROR_CLIENT_EXPECTATION_FAILED = 417;
	const I_AM_A_TEAPOT = 418;
	const UNPROCESSABLE_ENTITY = 422;
	const LOCKED = 423;
	const FAILED_DEPENDENCY = 424;
	const UNORDERED_COLLECTION = 425;
	const UPGRADE_REQUIRED = 426;
	const PRECONDITION_REQUIRED = 428;
	const TOO_MANY_REQUESTS = 429;
	const REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
	const ERROR_SERVER_INTERNAL_ERROR_SERVER = 500;
	const ERROR_SERVER_NOT_IMPLEMENTED = 501;
	const ERROR_SERVER_BAD_GATEWAY = 502;
	const ERROR_SERVER_SERVICE_UNAVAILABLE = 503;
	const ERROR_SERVER_GATEWAY_TIMEOUT = 504;
	const ERROR_SERVER_HTTP_VERSION_NOT_SUPPORTED = 505;
	const VARIANT_ALSO_NEGOTIATES = 506;
	const INSUFFICIENT_STORAGE = 507;
	const LOOP_DETECTED = 508;
	const NETWORK_AUTHENTICATION_REQUIRED = 511;
}
